### ISSUE TITLE
How to make shopify store link with MOL pay? 

### ISSUE THREAD

**Issue by wellionthai** [RazerMS/Documentation-RazerMS_API_Spec#11]
Hello experts. My store is already connected to the payment method of MOL Pay. But after the customer pays, it cannot be redirected from MOL Pay to Shopify to confirm that the payment was successful. Therefore, the system prompts that the payment has failed, and there is no order record in the Shopify background. I would like to ask for help with the Return URL.

**Comment by wankimmy** [comment]
hi @wellionthai , you can refer our latest guide in this link, need to ensure you follow the steps correctly - https://github.com/RazerMS/Shopping-Cart-Plugins-RazerMS_Hosted_Payment_for_Shopify/wiki/Hosted-Payment-for-Shopify-Guide-2022

if the issue still occur, you may share your shopify website in order for us to test it
