### ISSUE TITLE
what is the pay response？

### ISSUE THREAD

**Issue by bladeandmaster88** [RazerMS/Documentation-RazerMS_API_Spec#13]
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/20092047/191401672-dd3b665b-bf8c-472b-9eec-61632a50ebe2.png">

From the picture above, I can only see the payment request parameters, but I can not see the results returned by the payment request.

**Comment by Kheechieng** [comment]
![image](https://user-images.githubusercontent.com/19460508/191721670-e6696453-838c-4ac8-b124-097184f5eced.png)

@bladeandmaster88 you can get the result payload from this page onwards.
