### ISSUE TITLE
How to set card payment option in hosted payment page

### ISSUE THREAD

**Issue by azrul** [RazerMS/Documentation-RazerMS_API_Spec#15]
Is there a way to skip payment method selection and go straight to credit card payment when using hosted payment page?

I tried to add the payment method filename on https://pay.merchant.razer.com/RMS/pay/MerchantID/Payment_Method URL but it still shows the payment method selection.

Adding the `channel` parameter also does nothing except show an error if the channel is not supported.

ps:// the real goal here is to enforce a RM1 card payment and enforce tokenization of the card.

**Comment by Kheechieng** [comment]
Hi @azrul you might want to consider using another integration method which is seamless integration, by this method user won't be seeing RMS hosted page (channel selection page) and will straight redirect user to card number input page, or online banking page based on the `mpschannel` parameter.

https://github.com/RazerMS/Integration-RazerMS_JavaScript_Seamless_Integration

**Comment by azrul** [comment]
Looks like that's the only way to do this. Thanks.
