### ISSUE TITLE
Your transaction has been denied due to merchant account issue (P02)

### ISSUE THREAD

**Issue by zlnmg** [RazerMS/Documentation-RazerMS_API_Spec#17]
Dear manager:

     My Merchant id is  already go live now。

    l   already try txtChannel in“creditAl，“CREDITW”，“creditT” ，But they all return error with “P02  Your transaction has been denied due to merchant account issue (P02)。 ls My Merchant right ? it is already go live now. how can i do ?

**invoke url** :  https://pay.merchant.razer.com/RMS/API/Direct/1.4.0/index.php

**request data** : MerchantID=twi@@@ble&ReferenceNo=Rz20221201675644&TxnType=SALS&TxnChannel=creditT&TxnCurrency=USD&TxnAmount=1.50&CustName=limingzhang&Custemail=z@@@022@gmail.com&CustContact=1@@@570&CustDesc=@@@&ReturnURL=http://@@@/return&NotificationURL=https://@@@/razer&CC_PAN=5329@@@91&CC_CVV2=2**&CC_MONTH=11&CC_YEAR=24&non_3DS=1&ProductDesc=BlazerDressBaby&Signature=75b50d95ff984d9985a7029f577b4fcf

**response data**：{"status":false,"error_code":"P02","error_desc":"Your transaction has been denied due to merchant account issue (P02)"}

**Comment by Kheechieng** [comment]
@zlnmg sometimes its due to the currency USD which is not enabled for your merchant ID, you may send an email to support-sa@razer.com for us to further check on the setting for your merchant ID
