### ISSUE TITLE
Clarify Questions

### ISSUE THREAD

**Issue by taishjason** [RazerMS/Documentation-RazerMS_API_Spec#21]
It is possible to have same email address (bill_email) for Payment Page Integration? 

[Referring to Documentation](https://github.com/RazerMS/Documentation-RazerMS_API_Spec/blob/main/%5Bofficial%20API%5D%20Razer%20API%20Spec%20for%20Merchant%20(v13.39).pdf) at page 30

**Comment by Kheechieng** [comment]
@taishjason The billing email is not a mandatory field and can be made optional upon request (by sending email to support-sa@razer.com). To answer your questions, yes it is possible to have same email address for different transactions.
