### ISSUE TITLE
Any incorrect payload?

### ISSUE THREAD

**Issue by alanwsh** [RazerMS/Documentation-RazerMS_API_Spec#22]
$vcode = md5('3.99**MERCHANTID**TestOrder**VERIFYKEY**');
form action="https://pay.merchant.razer.com/RMS/pay/**MERCHANTID**" id="form" method="post">
input type="hidden" name="merchant_id" value="**MERCHANTID**">
input type="hidden" name="amount" value="3.99">
input type="hidden" name="orderid" value="TestOrder">
input type="hidden" name="bill_name" value="Dummy Bill Name">
input type="hidden" name="bill_email" value="dummy@gmail.com">
input type="hidden" name="bill_mobile" value="0123456789">
input type="hidden" name="bill_desc" value="Payment">
input type="hidden" name="country" value="MY">
input type="hidden" name="vcode" value="{{$vcode}}">
/form>

But I'm getting **Your payment info format is not correct !**, 
Following the documentation, I went to this link **https://api.merchant.razer.com/RMS/query/vcode.php** to check the generated vcode and it shows 
![image](https://github.com/RazerMS/Documentation-RazerMS_API_Spec/assets/72345813/501f5cca-f2a2-4855-b2de-5119880d8fa8)

If you have any idea is it anything wrong on other inputs? The merchant id and verify key is correct just that I'm not showing here

**Comment by Kheechieng** [comment]
Can you make sure the vcode is in lower case characters? If its still not working in lower case appreciate you could send an email to support-sa@razer.com and provide your full payload including merchant ID for us to take a look.
