### ISSUE TITLE
merchant.razer.com/v3/

### ISSUE THREAD

**Issue by NSGGLOBAL** [RazerMS/Documentation-RazerMS_API_Spec#7]

**Comment by NSGGLOBAL** [comment]
RazerV3

**Comment by wankimmy** [comment]
hi @NSGGLOBAL , may I know is there any issue that you are facing in this repo?

**Comment by NSGGLOBAL** [comment]
How to login v3
How to use Razer casz

**Comment by wankimmy** [comment]
Hi @NSGGLOBAL , to login as our merchant, you can login using this link https://portal.merchant.razer.com/index.php?mod=authentication&opt=login

if you want to know the channels that we provided and onboard with us, you may send an email to sales-sa@razer.com

**Comment by wankimmy** [comment]
Hi @NSGGLOBAL , if there is no enquiry i will close this issue
